#!/usr/bin/env node

const data = process.argv.slice(-1)[0];
const crypto = require('crypto');

console.log(crypto.createHash('md5').update(data).digest('hex'));
console.log(crypto.createHash('sha1').update(data).digest('hex'));
console.log(crypto.createHash('sha256').update(data).digest('hex'));
console.log(crypto.createHash('md5').update(data).digest('base64'));
