#!/usr/bin/env node

const hex = require('crypto-js/enc-hex');
const utf8 = require('crypto-js/enc-utf8');
const base64 = require('crypto-js/enc-base64');
const md5 = require('crypto-js/md5');
const sha1 = require('crypto-js/sha1');
const sha256 = require('crypto-js/sha256');

const data = process.argv.slice(-1)[0];

console.log(`base64 '${data}'`, base64.stringify(utf8.parse(data)));
console.log(`md5    '${data}'`, hex.stringify(md5(data)));
console.log(`sha1   '${data}'`, hex.stringify(sha1(data)));
console.log(`sha256 '${data}'`, hex.stringify(sha256(data)));
console.log(`b64 md5'${data}'`, base64.stringify(md5(data)));
